spring:
  datasource:
    url: jdbc:mysql://mysql:3306/technologydb
    username: root
    password: root
  jpa:
    show-sql: true
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate:
        ddl-auto: create
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl