spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gestionuser?serverTimezone=UTC
    username: root
    password:
  jpa:
    show-sql:
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate:
        ddl-auto: update
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl