spring:
  datasource:
    url: jdbc:mysql://localhost:3306/technologydb?createDatabaseIfNotExist=true
    username: root
    password: root123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
